version: "3.9"

services:
  yolo-api:
    build: .
    container_name: yolo-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./results:/app/results   # lưu video kết quả
    # deploy:                     # Bỏ comment nếu có GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]