version: "3.9"

services:
  finger-count:
    build: .
    container_name: finger-count-live
    ports:
      - "8000:8000"
    restart: unless-stopped
    privileged: true                    # Quan trọng để truy cập camera
    devices:
      - /dev/video0:/dev/video0         # Camera
    environment:
      - DISPLAY=${DISPLAY}